spring:
  application:
    name: shopping-list-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: false